version: 2.1

jobs:
  gather:
    parameters:
      platform:
        type: string
    docker:
      - image: <<parameters.platform>>
    steps:
      - checkout
      # Docker based images by default do not have lsmod or modprobe.
      # We need to install kmod so that the varnishgather can run in a container.
      - run: |
          if ! command -v lsmod &> /dev/null; then
            if command -v apt-get > /dev/null; then
              apt update -y
              apt install -y kmod
            else
              yum update -y
              yum install -y kmod
            fi
          fi
          set -x
          set -e
      # Why does the varnishgather exit with a non-zero status code, even if
      # it is successfull? For now, I'm ignoring the exit code to make progress
      # on the CircleCi configuration.
      - run: ./varnishgather || true
      - run: |
          mkdir -p gathers/<<parameters.platform>>
          mv *.tar.gz gathers/<<parameters.platform>>/
      - persist_to_workspace:
          root: ./
          paths:
            - gathers
  test:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - attach_workspace:
          at: ./gathers
      - run: python tests.py "gathers"

workflows:
  test:
    jobs:
      - gather:
          matrix:
            parameters:
               platform: [
                  "debian:jessie", "debian:bullseye", "debian:buster", "debian:stretch",
                  "ubuntu:trusty", "ubuntu:bionic", "ubuntu:focal", "ubuntu:xenial",
                  "centos:7", "centos:8",
                  "rockylinux:8"
               ]
      - test:
          requires: ["gather"]
