version: 2.1

jobs:
  gather:
    parameters:
      platform:
        type: string
      install:
        type: string
    docker:
      - image: <<parameters.platform>>
    steps:
      - checkout
      # Docker based images by default do not have lsmod or modprobe.
      # We need to install kmod so that the varnishgather can run in a container.
      - run:
          name: "Install dependencies"
          command: |
            set -e
            if command -v apt-get > /dev/null; then
              apt update -y
              apt install -y kmod curl
              if [ ! -z "<<parameters.install>>" ]; then
                curl https://docs.varnish-software.com/scripts/setup.sh | TOKEN=$PROJECT_PACKAGECLOUD_TOKEN INSTALL=<< parameters.install >> bash
              fi
            else
              yum update -y
              yum install -y kmod curl
            fi
      # Why does the varnishgather exit with a non-zero status code, even if
      # it is successfull? For now, I'm ignoring the exit code to make progress
      # on the CircleCi configuration.
      - run: ./varnishgather || true
      - run:
          name: "Collect gather"
          command: |
            mkdir -p gathers/<<parameters.platform>>
            mv *.tar.gz gathers/<<parameters.platform>>/
      - persist_to_workspace:
          root: ./
          paths:
            - gathers
  test:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - attach_workspace:
          at: ./gathers
      - run: python tests.py "gathers"

workflows:
  test:
    jobs:
      - gather:
          matrix:
            parameters:
              install: [
                "",
                "varnish-plus",
              ]
              platform: [
                "debian:jessie", "debian:bullseye", "debian:buster", "debian:stretch",
                "ubuntu:trusty", "ubuntu:bionic", "ubuntu:focal", "ubuntu:xenial",
                "centos:7", "centos:8",
                "rockylinux:8"
              ]
      - test:
          requires: ["gather"]
